version: '3'
services:
  demo-app: 
    build: .
    volumes:
      - .dockerenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true  # 環境によってホットリロードのために必要